Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "lamp.dev"
  config.vm.network "private_network", ip: "192.168.80.80"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.synced_folder "../", "/var/www/lamp.dev", owner: "www-data", group: "www-data"
  config.vm.provision "shell", path: "lamp.sh"
  config.vm.provision "shell", inline: "service apache2 restart", run: "always"

end